// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFbv9vEI8sd0zijGUfHx4lRcedggyo_80',
    appId: '1:777014175458:web:879ebc654a06283020a0bb',
    messagingSenderId: '777014175458',
    projectId: 'proflie-8b7c6',
    authDomain: 'proflie-8b7c6.firebaseapp.com',
    storageBucket: 'proflie-8b7c6.firebasestorage.app',
    measurementId: 'G-TFKMX83KZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqyuIGIjspkeYs9Gw7KEF3kRbxCnX6rT0',
    appId: '1:777014175458:android:3d91aaa15132649c20a0bb',
    messagingSenderId: '777014175458',
    projectId: 'proflie-8b7c6',
    storageBucket: 'proflie-8b7c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBsOZ3HsDoFShE6b8of6h1D9Sj8EHzqbw',
    appId: '1:777014175458:ios:258f64c4926e371120a0bb',
    messagingSenderId: '777014175458',
    projectId: 'proflie-8b7c6',
    storageBucket: 'proflie-8b7c6.firebasestorage.app',
    iosBundleId: 'com.example.oanhFile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBsOZ3HsDoFShE6b8of6h1D9Sj8EHzqbw',
    appId: '1:777014175458:ios:258f64c4926e371120a0bb',
    messagingSenderId: '777014175458',
    projectId: 'proflie-8b7c6',
    storageBucket: 'proflie-8b7c6.firebasestorage.app',
    iosBundleId: 'com.example.oanhFile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFbv9vEI8sd0zijGUfHx4lRcedggyo_80',
    appId: '1:777014175458:web:0a9137e4fcaf79d320a0bb',
    messagingSenderId: '777014175458',
    projectId: 'proflie-8b7c6',
    authDomain: 'proflie-8b7c6.firebaseapp.com',
    storageBucket: 'proflie-8b7c6.firebasestorage.app',
    measurementId: 'G-GJGF62S88F',
  );
}
